---

- hosts: all
  become: true
  pre_tasks:
  
  - name: update repository cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"
    
- hosts: all
  become: true
  roles:
    - base
        
- hosts: chia_server
  become: true
  roles:
    - chia_server