---

- hosts: all
  become: true
  tasks:
  
  - name: remove apache and php packages for Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: absent
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
