- name: Adding Universe repository for exfat
  shell: add-apt-repository universe -y
  changed_when: false

- name: Install exFat
  tags: always
  apt:
    name:
      - exfat-fuse
      - exfat-utils
    state: latest
    update_cache: yes
    
- name: Git checkout of the Chia Network
  ansible.builtin.git:
    repo: 'https://github.com/Chia-Network/chia-blockchain.git'
    dest: /git/chia-blockchain
    version: latest
    recursive: yes

#ssh into server
#sh install.sh
#byobu
#. ./activate
#chia init