- name: add ssh key for ansible
  authorized_key:
    user: ansible
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMHch5ChFgehKbhkrbnf/DTTs07U1fyqyNa1G49fU2aZ ansible"

- name: Install useful packages
  tags: always
  apt:
    name: 
      - git
      - byobu
      - htop
      - glances
      - chkrootkit
    state: latest
    update_cache: yes
